version: '3.3'

services:
    jenkins_comp:
        build:
            context: .
        image: jenkins_comp:latest
        volumes:
            - /jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8080:8080
            - 50000:50000
